<?
/**
 * Implements hook_help().
 */
function first_help($path, $arg) {
    if ($path == 'admin/help#first') {
        $output = '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('The First module show how to create forms using Drupal') . '</p>';
        return $output;
    }
}

/**
 * Implements fo hook_menu().
 */
function first_menu() {
    $items['form1'] = array(
        'type' => MENU_CALLBACK,
        'acess arguments' => array('access content'),
        'page callback' => 'first_form',
        'page arguments' =>array('first_form1'));
       return $items;
}
  function first_form() {
      $form = array();

      $form['name']=array(
          '#type' =>'textfield',
          '#title' =>t('Enter Your Name'),
          '#description'=>t('Your First name goes here')
      );
      $form['last_name']=array(
          '#type' =>'textfield',
          '#title' =>t('Enter Your Last Name'),
          '#description'=>t('Your last name goes here')
      );
      $form['email']=array(
          '#type' =>'textfield',
          '#title' =>t('Enter Your email'),
          '#description'=>t('Your email ID goes here')
      );
      $form['Country']=array(
          '#type' =>'select',
          '#title' =>t('Select Your Country'),
          '#options'=>array('USA','UK','France','Japan')
      );

      $form['submit']=array(
          '#type'=>'submit',
          '#value'=>t('Submit')
      );
      return $form;
  }
?>
